name: Docker-Login-Build-Push

on:
  push:
    branches: [main]

env:
  # variable holding my repo folder name (using DockerHub is assumed)
  DOCKER_HUB_REPO: markpeterangeloproject5
# jobs - each jobs runs on a runner - parralel by deafult, can be dependent based on id
#     https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobs
jobs:
  build_and_push:
    name: Build docker image and push to Docker Hub
    # OS of runner
    runs-on: ubuntu-latest
    steps:
      # checkout repo contents to runner
      - 
        name: Checkout repo to runner
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Login in to DockerHub, credentials stored as GitHub repository secrets
      #    Usage documentation: https://github.com/marketplace/actions/docker-login
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Build and push
 
        id: docker_build 
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:latest
